sudo: required
services:
    - docker

before_install: 
    - docker build -t obusorezekiel/dockerr-react -f Dockerfile.dev .

script:
    - docker run -e CI=true obusorezekiel/dockerr-react npm run test -- --coverage
